name: 'blog'
mode: 'dev'
port: 8080
version: 'v0.1.0'
start_time: '2023-09-22'
machine_id: 1

auth:
  jwt_access_expire: 336
  jwt_refresh_expire: 720
  jwt_key: 'blog_secret'
mysql:
  host: '127.0.0.1'
  port: 3306
  user: 'root'
  password: 'fishpwd4321..'
  db_name: 'blog'
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: '127.0.0.1'
  port: 6379
  password: ''
  db: 0
  poll_size: 100
log:
  level: 'debug'
  filename: 'tmp/blog.log'
  max_size: 200
  max_age: 30
  max_backups: 7
  Compress: false
